ffmpeg: fix build for missing packet_internal.h
fix following build error

libavcodec/libsvt_av1.c:416:5: error: implicit declaration of function ‘ff_side_data_set_encoder_stats’ [-Werror=implicit-function-declaration]
     ff_side_data_set_encoder_stats(pkt, headerPtr->qp * FF_QP2LAMBDA, NULL, 0, pict_type);

since following commit in ffmpeg

commit 6e1903938befc0bce2f64e01770af2f65d625cfc
Author: James Almer <jamrial@gmail.com>
Date:   Tue Jun 2 18:38:33 2020 -0300

    avcodec/internal: move packet related functions to their own header

    Signed-off-by: James Almer <jamrial@gmail.com>